#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0:focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0:focal AS build
WORKDIR /src
COPY ["Test.MVC/Test.MVC.csproj", "Test.MVC/"]
RUN dotnet restore "Test.MVC/Test.MVC.csproj"
COPY . .
WORKDIR "/src/Test.MVC"
RUN dotnet build "Test.MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Test.MVC.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Test.MVC.dll"]